---
driver:
  name: docker

provisioner:
  name: chef_zero

driver_config:
  use_sudo: false

platforms:
  - name: debian-7
    run_list:
      - recipe[apt]
      - recipe[netstat]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
      - recipe[netstat]
  - name: centos-6.7
    run_list:
      - recipe[yum]
      - recipe[netstat]
  - name: centos-7.1
    driver_config:
      provision_command:
        - yum install -y iproute
    run_list:
      - recipe[yum]
      - recipe[netstat]

suites:
  - name: default
    run_list:
      - recipe[git]
      - recipe[integration_test]
  - name: from_source
    run_list:
      - recipe[integration_test::from_source]
