---
driver:
  name: docker

provisioner:
  name: chef_zero

driver_config:
  #  binary: docker.io
  use_sudo: false

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
      - recipe[git]
  - name: centos-7.1
    run_list:
      - recipe[yum]
      - recipe[git]

suites:
  - name: default
    run_list:
      - recipe[application_ruby_test::samson]
