---
driver:
  name: docker

provisioner:
  name: chef_zero

driver_config:
  use_sudo: false

platforms:
  - name: ubuntu-14.04
    driver_config:
      disable_upstart: false
      image: ubuntu-upstart:14.04
      run_command: /sbin/init
    run_list:
      - recipe[apt]
      - recipe[git]
  - name: centos-6.7
    driver: vagrant
    run_list:
      - recipe[yum]
      - recipe[git]
  - name: centos-7.1
    run_list:
      - recipe[yum]
      - recipe[git]

suites:
  - name: default
    run_list:
      - recipe[application_service_test::redmine]
